In [1]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns

import nltkl
from nltk.corpus import stopwords

from sklearn.feature_selection import mutual_info_classif

ModuleNotFoundError: No module named 'nltkl'

In [3]:
titles = pd.read_csv("titles-dropped.csv")
titles.head(100)

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
1,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['fantasy', 'action', 'comedy']",['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
3,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,tt0061578,7.7,72662.0,20.398,7.600
4,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,"['comedy', 'european']",['GB'],4.0,tt0063929,8.8,73424.0,17.617,8.306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,tm191110,Titanic,MOVIE,101-year-old Rose DeWitt Bukater tells the sto...,1997,PG-13,194,"['drama', 'romance']",['US'],NaN,tt0120338,7.9,1146825.0,155.683,7.878
96,ts34435,Cowboy Bebop,SHOW,"In 2071, roughly fifty years after an accident...",1998,TV-14,25,"['animation', 'action', 'scifi', 'western', 'c...",['JP'],1.0,tt0213338,8.9,115448.0,35.402,8.522
97,tm192037,Starship Troopers,MOVIE,"Set in the future, the story follows a young s...",1997,R,129,"['scifi', 'action', 'thriller']",['US'],NaN,tt0120201,7.3,291452.0,29.500,6.993
98,tm27395,Mission: Impossible II,MOVIE,With computer genius Luther Stickell at his si...,2000,PG-13,123,"['thriller', 'action']",['US'],NaN,tt0120755,6.1,337987.0,29.392,6.100
99,tm113513,Dumb and Dumber,MOVIE,Lloyd and Harry are two men whose stupidity is...,1994,PG-13,107,['comedy'],['US'],NaN,tt0109686,7.3,379999.0,31.852,6.600

Feature Filtering based on Mutual Information for classification and numerical models
Set up X-variable:"age_certification", "runtime", "genres", "production_countries" 
with respect Y-variable: "imdb_score", "imdb_votes", "tmdb_popularity", "tmdb_score".

In [5]:
THRESHOLD = 0.2

X = titles[["age_certification", "genres", "production_countries"]]
Y_imdb_score = titles["imdb_score"]
Y_imdb_votes = titles["imdb_votes"]
Y_tmdb_popularity = titles["tmdb_popularity"]
Y_tmdb_score = titles["tmdb_score"]

mi_arr = mutual_info_classif(X=X, y=Y_imdb_score, discrete_features=True)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.